backend:
    name: git-gateway
    branch: main # Branch to update (optional; defaults to master)
media_folder: public/images/uploads
public_folder: /images/uploads
collections:
    # - name: "pages"
    #   label: "Pages"
    #   files:
    #       - label: "Cats"
    #         name: "cats"
    #         file: "src/content/cats.md"
    #         fields:
    #             - { label: "Title", name: "title", widget: "string" }
    #             - { label: "Publish Date", name: "date", widget: "datetime" }
    #             - { label: "Body", name: "body", widget: "markdown" }
    #             - label: "Cats"
    #               name: "cats"
    #               widget: list
    #               fields:
    #                   - { label: "Name", name: "name", widget: "string" }
    #                   - {
    #                         label: "Description",
    #                         name: "description",
    #                         widget: "text",
    #                     }
    - label: "Portfolio"
      name: "portfolio"
      folder: "src/content/_posts/portfolio"
      create: true
      slug: "{{fields.slug}}"
      fields:
          - { label: "Slug (Translit)", name: "slug", widget: "string" }
          - label: "Service"
            name: "service"
            widget: "select"
            multiple: true
            options:
                - { label: "Аудит сайтов", value: "Аудит сайтов" }
                - { label: "Дизайн сайтов", value: "Дизайн сайтов" }
                - { label: "Разработка сайтов", value: "Разработка сайтов" }
                - {
                      label: "Разработка лендингов",
                      value: "Разработка лендингов",
                  }
                - { label: "Контакстная реклама", value: "Контакстная реклама" }
                - {
                      label: "Таргетированая реклама",
                      value: "Таргетированая реклама",
                  }
                - { label: "SEO продвижение", value: "SEO продвижение" }
                - {
                      label: "SMM (ведение профилей в соцсетях)",
                      value: "SMM (ведение профилей в соцсетях)",
                  }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Featured Image", name: "thumbnail", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Info"
            name: "info"
            widget: object
            fields:
                - { label: "Client", name: "client", widget: "string" }
                - { label: "Service", name: "service", widget: "string" }
                - {
                      label: "Deliverable(Результат)",
                      name: "deliverable",
                      widget: "string",
                  }
          - label: "Keywords"
            name: "keywords"
            widget: "select"
            multiple: true
            options:
                [
                    "Design",
                    "UI/UX",
                    "Wireframing",
                    "Branding",
                    "Development",
                    "webflow",
                    "Marketing",
                    "SMM",
                ]
    - label: "Services"
      name: "services"
      folder: "src/content/_posts/services"
      create: true
      slug: "{{fields.slug}}"
      fields:
          - { label: "Slug (Translit)", name: "slug", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Featured Image", name: "thumbnail", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
    - label: "Widgets"
      name: "widgets"
      files:
          - label: "Frequently asked questions"
            name: "faq"
            file: "src/content/widgets/faq.md"
            fields:
                - { label: "Title", name: "title", widget: "string" }
                - label: "Questions"
                  name: "content"
                  widget: list
                  fields:
                      - { label: "Question", name: "title", widget: "string" }
                      - { label: "Answer", name: "description", widget: "text" }
          - label: "Секция с формой для связи"
            name: "order_section"
            file: "src/content/widgets/order-section.md"
            fields:
                - { label: "Title", name: "title", widget: "string" }
                - { label: "Description", name: "description", widget: "text" }
                - { label: "Form title", name: "form_title", widget: "string" }
                - { label: "Form description", name: "form_description", widget: "text" }
