backend:
    name: git-gateway
    branch: main # Branch to update (optional; defaults to master)
media_folder: public/images/uploads
public_folder: /images/uploads
collections:
    - name: "pages"
      label: "Pages"
      files:
          - label: "Cats"
            name: "cats"
            file: "src/content/cats.md"
            fields:
                - { label: "Title", name: "title", widget: "string" }
                - { label: "Publish Date", name: "date", widget: "datetime" }
                - { label: "Body", name: "body", widget: "markdown" }
                - label: "Cats"
                  name: "cats"
                  widget: list
                  fields:
                      - { label: "Name", name: "name", widget: "string" }
                      - {
                            label: "Description",
                            name: "description",
                            widget: "text",
                        }
    - label: "Portfolio"
      name: "portfolio"
      folder: "src/content/_posts/portfolio"
      create: true
      fields:
      - {label: "Service", name: "service", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Info"
        name: "info"
        widget: object
        fields:
            - { label: "Client", name: "client", widget: "string" }
            - { label: "Service", name: "service", widget: "string" }
            - { label: "Deliverable(Результат)", name: "deliverable", widget: "string" }
    - label: "Services"
      name: "services"
      folder: "src/content/_posts/services"
      create: true
      fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
